### ISSUE TITLE
[BUG] Unable to connect to testnet

### ISSUE THREAD

**Issue by RinwaOwuogba** [NillionNetwork/client-ts#20]
**Describe the bug**
I am unable to connect to the nillion testnet following the react example in this repo.

**How to reproduce**
Add your steps to reproduce the behavior:
1. Go to the code sandbox https://codesandbox.io/p/devbox/8ctxxx
2. Fork the devbox
3. Go to src/nillion.ts, add your private key
4. Reload the app.
5. Click on connect to nillion.

**Expected behavior**
A successful connection. Which is required to be able to use the hooks exposed by the NIllionProvider.

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]

**Comment by tim-hm** [comment]
Our client doesn't working with vite currently -- if you can vanilla react or nextjs is working well. 

If you're fixed on vite, then I believe you can work around some of the issues but I haven't had time to investigate too deeply. Here's what I'd recommend:

1. Turn on logging: `localStorage.debug = "nillion:*"`
2.  Copy `@nillion/client-wasm/dist/index_bg.wasm` into `node_modules/.vite/deps`

This should get you to the point where the wasm bundle is loading. Next you'll need to address it's worker.js but I haven't had capacity to work my way through that issue.

**Comment by RinwaOwuogba** [comment]
I might be doing something wrong here but after following these steps and running `npm run dev` I see several errors e.g:

```ERROR in ./src/pages/store.tsx 3:0-160
Module not found: Error: Can't resolve '@nillion/client-react-hooks' in '/client-ts/examples/react/src/pages'
 @ ./src/pages/index.ts 4:0-24 4:0-24
 @ ./src/router.tsx 3:0-58 9:42-51 13:45-49 17:45-50 21:45-52
 @ ./src/app.tsx 6:0-34 13:62-68
 @ ./src/index.tsx 3:0-28 5:32-35```

Setup steps;
1. Cloned this repo.
2. Switched the `c4504cb88e84574668a345375d46d5135652748a` commit
3. Installed dependencies in root directory via `npm install`.
4. Switched to the react directory `examples/react`.

**Comment by tim-hm** [comment]
I recommending sticking with HEAD on main for your starting point. You'll see there that the react examples were removed to keep the maint burden manageable. I would copy the contents of the nextjs example into another folder and start there. If you keep them in the monorepo you may run into issues as the various @nillion/* dependencies will then need to be locally built.

We are starting to implement a `create-nillion-app` to bootstrap so this will get easier.
